import { validateSpot } from '@curve/contracts';

const sampleSpots = [
  { id: 'usui-old-road', name: '碓氷峠 旧道', area: '群馬県安中市', mode: 'sport', badge: 'おすすめ', photo: 'usui', distanceKm: 11.2, durationMinutes: 22, elevationGainM: 420, highlights: ['連続コーナー', '幅員 約5.5m', '標高差 420m'], start: '横川側入口', goal: '軽井沢側入口', sections: [{ name: '入口ヘアピン', radius: 'R=25m 目安', width: '幅員 約5.5m / 離合注意' }, { name: '中盤連続区間', radius: 'R=40–70m 目安', width: '勾配あり / 見通し注意' }], stops: [], source: 'UI検証用サンプル（公式道路情報で要確認）', verifiedAt: '2026-09-12', restrictionStatus: 'check-required' },
  { id: 'haruna-lake-line', name: '榛名山・榛名湖線', area: '群馬県高崎市', mode: 'sport', badge: '眺望', photo: 'haruna', distanceKm: 26.7, durationMinutes: 39, elevationGainM: 610, highlights: ['中速コーナー', '幅員 約6.0m', '標高差 610m'], start: '伊香保温泉側', goal: '榛名湖畔', sections: [{ name: '登坂区間', radius: 'R=50–90m 目安', width: '幅員 約6.0m' }, { name: '湖畔アプローチ', radius: '緩やかなカーブ', width: '歩行者・自転車に注意' }], stops: [], source: 'UI検証用サンプル（公式道路情報で要確認）', verifiedAt: '2026-09-12', restrictionStatus: 'check-required' },
  { id: 'akagi-south', name: '赤城南面・県道16号', area: '群馬県前橋市', mode: 'sport', badge: '朝がおすすめ', photo: 'akagi', distanceKm: 31.2, durationMinutes: 45, elevationGainM: 730, highlights: ['テクニカル', '幅員 約5.0m', '標高差 730m'], start: '前橋側入口', goal: '赤城山大沼', sections: [{ name: '南面登坂', radius: 'R=35–60m 目安', width: '幅員 約5.0m / 離合注意' }], stops: [], source: 'UI検証用サンプル（公式道路情報で要確認）', verifiedAt: '2026-09-12', restrictionStatus: 'check-required' },
  { id: 'okutone-yukemuri', name: '奥利根ゆけむり街道', area: '群馬県みなかみ町', mode: 'drive', badge: '紅葉名所', photo: 'okutone', distanceKm: 12.8, durationMinutes: 20, elevationGainM: 280, highlights: ['渓谷ビュー', '道の駅あり', '温泉 3ヶ所'], start: '水上温泉郷', goal: '宝川温泉方面', sections: [], stops: [{ name: '道の駅 みなかみ水紀行館', detail: '休憩・軽食' }, { name: '渓谷展望ポイント', detail: '景観 / 駐車可否は現地確認' }], source: 'UI検証用サンプル（施設公式情報で要確認）', verifiedAt: '2026-09-12', restrictionStatus: 'check-required' },
  { id: 'haruna-panorama', name: '榛名湖パノラマライン', area: '群馬県高崎市', mode: 'drive', badge: '湖畔', photo: 'haruna', distanceKm: 27.1, durationMinutes: 42, elevationGainM: 510, highlights: ['湖畔ビュー', 'カフェあり', '展望台 2ヶ所'], start: '伊香保側', goal: '榛名湖畔', sections: [], stops: [{ name: '榛名湖畔', detail: 'カフェ・散策' }, { name: '湖畔展望台', detail: '眺望 / 駐車場あり' }], source: 'UI検証用サンプル（施設公式情報で要確認）', verifiedAt: '2026-09-12', restrictionStatus: 'check-required' },
  { id: 'akagi-plateau', name: '赤城高原ルート', area: '群馬県沼田市', mode: 'drive', badge: '寄り道', photo: 'akagi', distanceKm: 34.6, durationMinutes: 52, elevationGainM: 340, highlights: ['高原ビュー', '牧場あり', '道の駅あり'], start: '沼田側', goal: '赤城高原', sections: [], stops: [{ name: '道の駅 白沢', detail: '休憩・特産品' }, { name: '高原牧場', detail: '季節営業は要確認' }], source: 'UI検証用サンプル（施設公式情報で要確認）', verifiedAt: '2026-09-12', restrictionStatus: 'check-required' }
];

export const spots = sampleSpots.map(validateSpot);
